services:
  #backend
  backend:
    container_name: autominder_backend
    build: ./backend
    ports:
      - 4201:4201
    volumes:
      - ./backend:/admin
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2-alpine3.18
    restart: always
    container_name: autominder_postgres
    environment:
      - POSTGRES_HOST:127.0.0.1
      - POSTGRES_USER=ignacio
      - POSTGRES_PASSWORD=06072001
      - POSTGRES_DB=autominder
    ports:
      - 5433:5432
