services:
  backend:
    container_name: autominder_backend
    build: ./backend
    ports:
      - 4201:4201
    volumes:
      - ./backend:/admin
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - autominder_networks

  postgres:
    image: postgres:16.2-alpine3.18
    restart: always
    env_file: ./backend/.env
    container_name: autominder_postgres
    environment:
      POSTGRES_USER: ignacio
      POSTGRES_PASSWORD: ignacio
      POSTGRES_DB: autominder
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ignacio -d autominder"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - autominder_networks

  #frontend
  frontend:
    container_name: autominder_frontend
    build: ./front
    ports:
      - 8081:8081
    volumes:
      - ./front:/app-ui
    networks:
      - autominder_networks

networks:
  autominder_networks:
    driver: bridge
